#!/usr/bin/env bash
# shellcheck disable=SC1090

set -e
set -o pipefail

# chooses a user account to use for the installation
get_user() {
    if [ -z "${TARGET_USER-}" ]; then
        PS3='Which user account should be used? '
        mapfile -t options < <(find /home/* -maxdepth 0 -printf "%f\\n" -type d)
        select opt in "${options:?[@]}"; do
            readonly TARGET_USER=$opt
            break
        done
    fi
}

# checks if we are running as root
check_is_sudo() {
    if [ "$(id -u)" -ne 0 ]; then
        echo "Please run as root."
        exit
    fi
}

# checks if we are running without
check_isnt_sudo() {
    if [ "$(id -u)" -eq 0 ]; then
        echo "Please run without root."
        exit
    fi
}

# sets up the base third-party software sources
setup_sources_base() {
    apt update
    apt upgrade -y
    apt install -y \
        curl \
        wget \
        snapd \
        apt-transport-https \
        ca-certificates \
        software-properties-common

    # docker
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu cosmic edge" > /etc/apt/sources.list.d/docker.list

    # git
    add-apt-repository ppa:git-core/ppa -y -n

    # fish
    apt-add-repository ppa:fish-shell/release-3 -y -n

    # git-lfs
    curl -fsSL https://packagecloud.io/github/git-lfs/gpgkey | apt-key add -
    echo "deb https://packagecloud.io/github/git-lfs/ubuntu/ cosmic main" > /etc/apt/sources.list.d/git-lfs.list

    # yarn
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
}

# sets up third-party software sources
setup_sources() {
    setup_sources_base;

    # chrome
    curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list

    # obs
    add-apt-repository ppa:obsproject/obs-studio -y -n

    # sublime text
    curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
    echo "deb https://download.sublimetext.com/ apt/stable/" > /etc/apt/sources.list.d/sublime-text.list

    # insync
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ACCAF35C
    echo "deb http://apt.insynchq.com/ubuntu artful non-free contrib" > /etc/apt/sources.list.d/insync.list
}

# installs the base packages
base() {
    apt update
    apt upgrade -y
    apt install -y \
        xsltproc \
        earlyoom \
        fop \
        pv \
        libelf-dev \
        libcap-dev \
        libcurl4-openssl-dev \
        r-base \
        linux-tools-common \
        linux-tools-generic \
        "linux-tools-$(uname -r)" \
        binutils-multiarch \
        uuid-dev \
        icu-devtools \
        libunwind8 \
        libunwind-dev \
        libbsd-dev \
        libedit-dev \
        libxml2-dev \
        libxml2-utils \
        swig \
        pkg-config \
        ninja-build  \
        python \
        libpython-dev \
        clang \
        libicu-dev \
        software-properties-common \
        libssh2-1-dev \
        libgit2-dev \
        cmake \
        libcurl4 \
        liblttng-ust0 \
        libpcap-dev \
        graphviz \
        readline-common \
        ncurses-base \
        openssl \
        libyaml-dev \
        libgmp-dev \
        libxslt1-dev \
        libxslt1-dev \
        libffi-dev \
        libtool \
        unixodbc \
        unixodbc-dev \
        m4 \
        zlib1g-dev \
        zlibc \
        libncurses5-dev \
        libsecret-1-dev \
        libwxgtk3.0-dev \
        libgl1-mesa-dev \
        libglu1-mesa-dev \
        libpng-dev \
        git-extras \
        python3 \
        fish \
        python3-pip \
        libssh-dev \
        htop \
        aspell \
        aspell-pt-pt \
        p7zip-full \
        jq \
        tmux \
        imagemagick \
        openjdk-8-jdk \
        openjdk-8-jre \
        ffmpeg \
        tree \
        dos2unix \
        pcregrep \
        linux-image-extra-virtual \
        libssl-dev \
        libbz2-dev \
        libreadline-dev \
        libsqlite3-dev \
        llvm \
        libncursesw5-dev \
        xz-utils \
        systemtap \
        tk-dev \
        git \
        git-lfs \
        inotify-tools \
        docker-ce \
        build-essential \
        dstat \
        automake \
        autoconf \
        vim \
        exuberant-ctags \
        libopenblas-base \
        libopenblas-dev \
        gdb \
        rlwrap \
        libu2f-host-dev \
        gnupg2 \
        pcscd \
        pcsc-tools \
        scdaemon \
        gnuplot \
        valgrind \
        lldb \
        ncdu \
        ranger \
        xdot \
        yarn \
        libpq-dev \
        postgresql-client-common \
        postgresql-client-10 \
        squashfs-tools \
        opensc \
        mosh \
        lnav \
        libjemalloc-dev \
        "linux-headers-$(uname -r)"

    truncate -s 0 /etc/sysctl.conf
    {
        # run perf without root
        echo "kernel.perf_event_paranoid = -1"
        echo "kernel.kptr_restrict=0"

        # elasticsearch
        echo "vm.max_map_count=262144" >> /etc/sysctl.conf

        # inotify limits
        echo "fs.inotify.max_user_watches = 1048576" >> /etc/sysctl.conf
    } >> /etc/sysctl.conf
    sysctl -p

    # config earlyoom
    echo "EARLYOOM_ARGS=\"-m 2 -r 30 --avoid '(^|/)(init|Xorg|ssh|sublime_text)$' --prefer '(^|/)(java|chrome)$'\"" > /etc/default/earlyoom

    # locally install git-lfs
    sudo su "$TARGET_USER" -c "git lfs install"

    # heroku
    snap install heroku --classic

    # firefox send
    snap install ffsend

    # asciinema
    snap install asciinema --classic

    # edge shellcheck
    snap install --channel=edge shellcheck --classic

    # google-cloud-sdk
    snap install google-cloud-sdk --classic

    # hugo
    snap install hugo --classic

    # setup docker for non-root
    usermod -aG docker "$TARGET_USER"

}

# installs all the packages
full() {
    base;

    apt install -y \
        mpv \
        alsa-tools-gui \
        pavucontrol \
        fonts-hack-ttf \
        ttf-ubuntu-font-family \
        snapd-xdg-open \
        google-chrome-stable \
        chrome-gnome-shell \
        gnome-clocks \
        gnome-tweaks \
        vanilla-gnome-default-settings \
        gnome-session \
        arandr \
        xclip \
        qemu-kvm \
        calibre \
        obs-studio \
        ubuntu-restricted-extras \
        transmission \
        insync \
        insync-nautilus \
        ofono \
        ofono-phonesim \
        sublime-text \
        sublime-merge

    # setup keyboard
    sed -i 's/XKBOPTIONS=.*/XKBOPTIONS="compose:ralt,caps:none"/g' /etc/default/keyboard
    sed -i 's/XKBLAYOUT=.*/XKBLAYOUT="us"/g' /etc/default/keyboard
    dpkg-reconfigure keyboard-configuration -f noninteractive

    echo "[phonesim]
Driver=phonesim
Address=127.0.0.1
Port=12345" > /etc/ofono/phonesim.conf

    # spotify
    snap install spotify --classic

    # discord
    wget -O discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"
    apt install -y ./discord.deb
    rm discord.deb

    sed -i 's/Exec=.*/Exec=env XDG_CURRENT_DESKTOP=Unity \/usr\/share\/discord\/Discord/g' /usr/share/applications/discord.desktop

    # set docker to autostart
    systemctl enable docker

    # set sublime text as default editor
    update-alternatives --install /usr/bin/editor editor /usr/bin/subl 90
    update-alternatives --set editor /usr/bin/subl

    # disable gnome dock
    apt remove gnome-shell-extension-ubuntu-dock

    # set login and lock screen to the gnome default
    update-alternatives --set gdm3.css /usr/share/gnome-shell/theme/gnome-shell.css

    # show nothing on grub boot
    sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT=""/g' /etc/default/grub
    update-grub

    # change plymouth background to black
    sed -i 's/black=.*/black=0x000000/g' /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth
    sed -i 's/white=.*/white=0xffffff/g' /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth
    sed -i 's/brown=.*/brown=0x000000/g' /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth
    sed -i 's/blue=.*/blue=0x000000/g' /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth
    update-initramfs -u

    # install and start tlp if we are on a laptop
    read -rp "Do you want to install TLP? (y/n) " -n 1
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        apt install -y tlp
        tlp start
    fi

}

# installs some extra fonts
install_fonts() {
    cd "$(dirname "${BASH_SOURCE[0]}")"
    cp -r .fonts/* /usr/share/fonts
    fc-cache -f -v
}

# checks if asdf is installed and installs it
check_asdf_and_install() {
    if [ ! -d "$HOME/.asdf" ]; then
        install_asdf
    fi
}

# checks if pyenv is installed and installs/updates it
check_pyenv_and_install() {
    if [ ! -d "$HOME/.pyenv" ]; then
        install_pyenv
    else
        update_pyenv
    fi
}

# checks if rbenv is installed and installs/updates it
check_rbenv_and_install() {
    if [ ! -d "$HOME/.rbenv/bin" ]; then
        install_rbenv
    else
        update_rbenv
    fi
}

# checks if rustup is installed and installs it
check_rustup_and_install() {
    if [ ! -d "$HOME/.rustup" ]; then
        install_rustup
    fi
}

# installs asdf
install_asdf() {
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.4.2
    . ~/.asdf/asdf.sh || true
    asdf update
}

# installs pyenv
install_pyenv() {
    curl -fsSL https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
    . ~/.config/fish/config.fish || true
}

update_pyenv() {
    (
        set -e
        cd "$(pyenv root)"
        git pull
    )
}

# installs rbenv
install_rbenv() {
    mkdir -p ~/.rbenv
    (
        cd ~/.rbenv
        git init
        git remote add origin https://github.com/rbenv/rbenv.git
        git fetch
        git branch master origin/master
        git checkout master
        src/configure && make -C src
        git clone https://github.com/rbenv/rbenv-default-gems.git plugins/rbenv-default-gems
        git clone https://github.com/rbenv/ruby-build.git plugins/ruby-build
    )
    . ~/.config/fish/config.fish || true
}

update_rbenv() {
    (
        set -e
        cd "$(rbenv root)" && git pull && src/configure && make -C src
        cd plugins/ruby-build && git pull
    )
}

# installs rustup
install_rustup() {
    curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path
    source "$HOME/.cargo/env" || true
}

# installs ruby
install_ruby() {
    rubyv="2.6.2"
    RUBY_CONFIGURE_OPTS="--with-jemalloc" rbenv install "$rubyv" --skip-existing || true
    rbenv global "$rubyv"
}

# installs go and some go packages
install_golang() {
    golangv="1.12.1"
    asdf plugin-add go https://github.com/kennyp/asdf-golang || true
    asdf install go "$golangv" || true
    asdf global go "$golangv"

    go get -u -v \
        honnef.co/go/tools/cmd/staticcheck \
        github.com/golangci/golangci-lint/cmd/golangci-lint \
        github.com/oxequa/realize \
        github.com/nektos/act \
        golang.org/x/tools/cmd/goimports \
        github.com/stamblerre/gocode \
        github.com/DarthSim/hivemind \
        github.com/DarthSim/overmind \
        github.com/go-delve/delve/cmd/dlv
}

# installs python and some python packages
install_python() {
    pythonv="3.7.2"
    pyenv install -s "$pythonv"
    pyenv global "$pythonv"

    pip install -U \
        pip \
        pipenv \
        py-spy \
        docker-compose \
        ipython \
        mypy \
        autopep8 \
        flake8 \
        awscli \
        aws-shell \
        matplotlib \
        httpie \
        isort \
        seashells \
        pgcli \
        litecli \
        wpm
}

# updates rustup and rust, also installs some rust packages
install_rust() {
    rustup self update
    rustup update

    rustup component add rls-preview rustfmt rust-analysis rust-src clippy llvm-tools-preview

    cargo install --force \
        cargo-binutils \
        cargo-fix \
        cargo-watch \
        cargo-release \
        cargo-fuzz \
        cargo-with \
        cargo-bloat \
        systemfd
}

# installs elixir and erlang
install_elixir() {
    erlangv="21.3"
    asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang || true
    asdf install erlang "$erlangv" || true
    asdf global erlang "$erlangv"

    elixirv="1.8.1"
    asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir || true
    asdf install elixir "$elixirv" || true
    asdf global elixir "$elixirv"

    mix local.hex --force
    mix local.rebar --force
    mix archive.install hex phx_new --force
    mix local.phx --force
}

# installs nodejs and some nodejs packages
install_nodejs() {
    nodejsv="11.10.1"
    asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git || true
    bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
    asdf install nodejs "$nodejsv" || true
    asdf global nodejs "$nodejsv"

    npm install -g @marp-team/marp-cli
}

# installs terraform and some kubernetes utilities
install_kube() {
    terraformv="0.11.11"
    asdf plugin-add terraform https://github.com/Banno/asdf-hashicorp.git || true
    asdf install terraform "$terraformv" || true
    asdf global terraform "$terraformv"
    terraform -uninstall-autocomplete || true
    terraform -install-autocomplete || true

    minikubev="0.34.1"
    asdf plugin-add minikube https://github.com/alvarobp/asdf-minikube.git || true
    asdf install minikube "$minikubev" || true
    asdf global minikube "$minikubev"

    kubectlv="1.13.4"
    asdf plugin-add kubectl https://github.com/Banno/asdf-kubectl.git || true
    asdf install kubectl "$kubectlv" || true
    asdf global kubectl "$kubectlv"

    helmv="2.13.0"
    asdf plugin-add helm https://github.com/Antiarchitect/asdf-helm.git || true
    asdf install helm "$helmv" || true
    asdf global helm "$helmv"
}

# updates the local dotfiles with the ones in the repository
get_dotfiles() {
    cd "$(dirname "${BASH_SOURCE[0]}")"

    rsync --exclude ".git/" \
        --exclude ".fonts/" \
        --exclude "install" \
        --exclude "README.md" \
        --exclude "LICENSE" \
        -avh --no-perms . ~

    if [ ! -f ~/.bin/ngrok ]; then
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip ngrok -d ~/.bin
        chmod a+x+r ~/.bin/ngrok
        rm ngrok-stable-linux-amd64.zip
    fi

    if [ ! -f ~/.bin/ctop ]; then
        wget -O ~/.bin/ctop "$(curl -s https://api.github.com/repos/bcicen/ctop/releases/latest | grep -oP "browser_download_url.*\K(https://.*linux-amd64)")"
        chmod a+x+r ~/.bin/ctop
    fi

    if [ ! -f ~/.bin/rbspy ]; then
        curl -L "$(curl -s https://api.github.com/repos/rbspy/rbspy/releases/latest | grep -oP "browser_download_url.*\K(https://.*unknown-linux-musl.tar.gz)")" | tar -xzf - -C ~/.bin
        chmod a+x+r ~/.bin/rbspy
    fi

    if [ ! -f ~/.bin/stern ]; then
        wget -O ~/.bin/stern "$(curl -s https://api.github.com/repos/wercker/stern/releases/latest | grep -oP "browser_download_url.*\K(https://.*linux_amd64)")"
        chmod a+x+r ~/.bin/stern
    fi

    if [ ! -f ~/.bin/wrk2 ]; then
        (
            cd ~/code
            if [ ! -d wrk ]; then
                git clone https://github.com/wg/wrk.git wrk
            fi
            cd wrk
            git pull
            make
            cp wrk ~/.bin/wrk
        )
    fi
}

usage() {
    echo -e "install\\n"
    echo "Usage:"
    echo "  linux                     - setup sources & install os pkgs"
    echo "  fonts                     - setup fonts"
    echo "  dotfiles                  - fetch dotfiles"
    echo "  python                    - install python and packages"
    echo "  golang                    - install golang and packages"
    echo "  rust                      - install rust and packages"
    echo "  nodejs                    - install nodejs"
    echo "  kube                      - install minikube, kubectl, etc"
    echo "  ruby                      - install ruby"
    echo "  elixir                    - install elixir"
}

main() {
    local cmd=$1

    if [[ -z "$cmd" ]]; then
        usage
        exit 1
    fi

    if [[ $cmd == "linux" ]]; then
        check_is_sudo
        get_user
        setup_sources
        full
        install_fonts
    elif [[ $cmd == "fonts" ]]; then
        check_is_sudo
        install_fonts
    elif [[ $cmd == "dotfiles" ]]; then
        check_isnt_sudo
        get_dotfiles
    elif [[ $cmd == "ruby" ]]; then
        check_isnt_sudo
        check_rbenv_and_install
        install_ruby
    elif [[ $cmd == "golang" ]]; then
        check_isnt_sudo
        check_asdf_and_install
        install_golang
    elif [[ $cmd == "python" ]]; then
        check_isnt_sudo
        check_pyenv_and_install
        install_python
    elif [[ $cmd == "rust" ]]; then
        check_isnt_sudo
        check_rustup_and_install
        install_rust
    elif [[ $cmd == "elixir" ]]; then
        check_isnt_sudo
        check_asdf_and_install
        install_elixir
    elif [[ $cmd == "nodejs" ]]; then
        check_isnt_sudo
        check_asdf_and_install
        install_nodejs
    elif [[ $cmd == "kube" ]]; then
        check_isnt_sudo
        check_asdf_and_install
        install_kube
    else
        usage
    fi
}

main "$@"
