#!/usr/bin/env bash
set -ue

MAC_ADDRESS="10:94:BB:97:9F:6A"
BLUEZ_CARD="bluez_card.${MAC_ADDRESS//:/_}"
BLUEZ_SINK="bluez_sink.${MAC_ADDRESS//:/_}.a2dp_sink"



setup_phonesim() {
  if ! command -v ofono-phonesim >/dev/null 2>&1; then
    sudo apt update
    sudo apt install ofono ofono-phonesim
    echo "[phonesim]
Driver=phonesim
Address=127.0.0.1
Port=12345" | sudo tee /etc/ofono/phonesim.conf

    echo "ofono-phonesim has been installed, please restart your machine"
  else
    echo "ofono-phonesim has already been setup"
  fi

  echo "[Unit]
Description=ofono-phonesim
After=ofono.service

[Service]
ExecStartPre=-pkill ofono-phonesim
ExecStart=ofono-phonesim -p 12345 /usr/share/phonesim/default.xml
ExecStartPost=/bin/sleep 2
ExecStartPost=dbus-send --print-reply --system --dest=org.ofono /phonesim org.ofono.Modem.SetProperty string:Powered variant:boolean:true

[Install]
WantedBy=multi-user.target" | sudo tee /etc/systemd/user/ofono-phonesim.service
  systemctl --user daemon-reload
  systemctl --user enable ofono-phonesim.service
}

start_phonesim() {
  if ! command -v ofono-phonesim >/dev/null 2>&1; then
    echo "Please run \`airpods setup\` and restart before running \`airpods start\`."
    exit 1
  fi

  pkill ofono-phonesim || true
  ofono-phonesim -p 12345 /usr/share/phonesim/default.xml &
  sleep 0.5

  dbus-send --print-reply --system --dest=org.ofono /phonesim org.ofono.Modem.SetProperty string:Powered variant:boolean:true || true

  echo "ofono-phonesim has successfully started"

  bluetoothctl disconnect "$MAC_ADDRESS"
  bluetoothctl connect "$MAC_ADDRESS"

  echo "bluetooth has successfully reconnected"
}

stop_phonesim() {
  pkill ofono-phonesim || true
}

a2dp() {
  if ! command -v ofono-phonesim >/dev/null 2>&1; then
    echo "Please run \`airpods setup\` and restart before running \`airpods a2dp\`."
    exit 1
  fi

  pacmd set-card-profile "$BLUEZ_CARD" a2dp_sink
}

headset() {
  if ! command -v ofono-phonesim >/dev/null 2>&1; then
    echo "Please run \`airpods setup\` and restart before running \`airpods hfp\`."
    exit 1
  fi

  pacmd set-card-profile "$BLUEZ_CARD" headset_head_unit
}

volume() {
  pactl set-sink-volume "$BLUEZ_SINK" "$1"
}

usage() {
  echo -e "airpods"
  echo -e ""
  echo -e "Usage:"
  echo -e "\t airpods <command>"
  echo -e ""
  echo -e "The commands are:"
  echo -e ""
  echo -e "\tsetup\tinstalls the required dependencies to make this work"
  echo -e "\tstart\tmakes sure the ofono-phonesim is running"
  echo -e "\tstop\tmakes sure the ofono-phonesim is not running"
  echo -e "\ta2dp\tset card profile to a2dp"
  echo -e "\thfp\tset card profile to headset/hfp"
  echo -e "\tvolume\tset pulseaudio volume"
}


main() {
  if [ "$#" -eq 0 ]; then
    usage
    exit 1
  else
    case $1 in
      "setup")
        setup_phonesim
        exit 0
      ;;
      "start")
        start_phonesim
        exit 0
      ;;
      "stop")
        stop_phonesim
        exit 0
      ;;
      "a2dp")
        a2dp
        exit 0
      ;;
      "hfp")
        headset
        exit
      ;;
      "help")
        usage
        exit 0
      ;;
      "volume")
        volume "$2"
        exit 0
      ;;
      *)
        usage
        exit 1
    esac
  fi
}

main "$@"
