#!/usr/bin/env bash
set -e
set -o pipefail

puxaforte() {
    git reset --hard "@{upstream}";
    git pull
}

usage() {
    echo "usage: git puxaforte"
}

version() {
    echo "puxaforte git plugin v0.1.0"
}

main() {
    if [ "$#" -eq 0 ]; then
        puxaforte
    fi

    case $1 in
        "-v"|"--version")
            version;
            exit 0
        ;;
        "-h"|"--help")
            usage;
            exit 0
        ;;
        *)
            usage;
            exit 1
        ;;
    esac
}

main "$@"
